-- Select the Sakila database
USE sakila;

-- Challenge 4.1 - List the number of films per category
SELECT 
    c.name AS category,
    COUNT(f.film_id) AS number_of_films
FROM film f
INNER JOIN film_category fc ON f.film_id = fc.film_id
INNER JOIN category c ON fc.category_id = c.category_id
GROUP BY c.name;

-- Challenge 4.2 - Retrieve store ID, city, and country for each store
SELECT 
    s.store_id,
    ci.city,
    co.country
FROM store s
INNER JOIN address a ON s.address_id = a.address_id
INNER JOIN city ci ON a.city_id = ci.city_id
INNER JOIN country co ON ci.country_id = co.country_id;

-- Challenge 4.3 - Calculate the total revenue generated by each store
SELECT 
    i.store_id,
    ROUND(SUM(p.amount), 2) AS total_revenue
FROM payment p
INNER JOIN rental r ON p.rental_id = r.rental_id
INNER JOIN inventory i ON r.inventory_id = i.inventory_id
GROUP BY i.store_id;

-- Challenge 4.4 - Determine the average running time of films for each category
SELECT 
    c.name AS category,
    ROUND(AVG(f.length), 2) AS avg_running_time
FROM film f
INNER JOIN film_category fc ON f.film_id = fc.film_id
INNER JOIN category c ON fc.category_id = c.category_id
GROUP BY c.name;

-- Challenge 4.5 BONUS - Film categories with the longest average running time
SELECT 
    c.name AS category,
    ROUND(AVG(f.length), 2) AS avg_running_time
FROM film f
INNER JOIN film_category fc ON f.film_id = fc.film_id
INNER JOIN category c ON fc.category_id = c.category_id
GROUP BY c.name
ORDER BY avg_running_time DESC;

-- Challenge 4.6 BONUS - Top 10 most frequently rented movies
SELECT 
    f.title,
    COUNT(r.rental_id) AS rental_count
FROM film f
INNER JOIN inventory i ON f.film_id = i.film_id
INNER JOIN rental r ON i.inventory_id = r.inventory_id
GROUP BY f.title
ORDER BY rental_count DESC
LIMIT 10;

-- Challenge 4.7 BONUS - Check if "Academy Dinosaur" can be rented from Store 1
SELECT 
    CASE
        WHEN COUNT(i.inventory_id) > 0 THEN 'Available'
        ELSE 'Not Available'
    END AS availability
FROM inventory i
INNER JOIN film f ON i.film_id = f.film_id
WHERE f.title = 'Academy Dinosaur'
  AND i.store_id = 1;

-- Challenge 4.8 BONUS - List all distinct film titles with availability status
SELECT 
    f.title,
    CASE 
        WHEN COUNT(i.inventory_id) = 0 THEN 'NOT available'
        ELSE 'Available'
    END AS availability
FROM film f
LEFT JOIN inventory i ON f.film_id = i.film_id
GROUP BY f.film_id, f.title
ORDER BY f.title;